name: 🐛 Bug Report
description: Report a bug or issue with the Dead Cells Test Framework
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have tested this on the latest version of the project
          required: true
        - label: I have followed the setup instructions in the README
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: unity-version
    attributes:
      label: Unity Version
      description: Which Unity version are you using?
      options:
        - Unity 2022.3.14f1 (LTS)
        - Unity 2022.3.20f1 (LTS)
        - Unity 2022.3.19f1 (LTS)
        - Unity 2023.1.x
        - Unity 2023.2.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you developing on?
      options:
        - Windows
        - macOS
        - Linux
        - Multiple platforms
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the framework is affected?
      options:
        - Player Controller
        - Combat System
        - Room/Level Management
        - LDtk Integration
        - Data-Driven Systems (CastleDB)
        - Animation System
        - Effects System
        - Build/Setup
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Please copy and paste any relevant console output or error messages
      placeholder: Paste console logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, project settings, etc.)
      placeholder: Any additional information that might help...